public class TryCatchExample {
    public static void main(String[] args) {
        try {
            // Code that may cause an exception
            int[] numbers = {1, 2, 3};
            System.out.println(numbers[4]); // Trying to access an index out of bounds
        } catch (ArrayIndexOutOfBoundsException e) {
            // Catch block handling the exception
            System.out.println("An ArrayIndexOutOfBoundsException occurred!");
        }
    }
}